### PR TITLE
transactions

### PR DESCRIPTION
**Pull request by isfgjspquzml**
transaction look like they work correctly with user and system breadcrumbs showing up in the transactions trace

### CODE REVIEW

**Comment by isfgjspquzml** [comment]
https://github.com/crittercism/crittercism-docs/pull/102

**Comment by isfgjspquzml** [comment]
I feel like the server side is inconsistent. Just tested iOS but I wasn't getting anything for a while. After I hook up charles and wait a bit I'm then seeing app loads etc. Anyways, can confirm that things are being sent as they should.

screen shot 2015-02-11 at 12 55 13 pm
screen shot 2015-02-11 at 12 55 25 pm
screen shot 2015-02-11 at 12 56 10 pm

**Comment by isfgjspquzml** [comment]
one issue is that system breadcrumbs aren't properly being tracked. I'm 100% sure i'm hitting begin transaction, then doing a background, then a foreground, and the failing the transaction but there are instances where they aren't catagorized into the right transaction

**Comment by isfgjspquzml** [comment]
This transaction has an extra 'background' breadcrumb

screen shot 2015-02-11 at 12 59 49 pm

and this transaction is missing a 'background' breadcrumb

screen shot 2015-02-11 at 12 59 55 pm

I'm gonna guess these system breadcrumbs are left asynchronously or somehting but I just wanted to point it out

**Comment by kellyroach** [comment]
BRIEF REVIEW
Briefly review "transactions" P.R.  DllImport's, more static public
API methods in CrittercismIOS.cs, more transactions-related buttons
placed on test app CrittercismTestGUI.cs, some guid's have changed
for GKW reason , and libCrittercismPlugin_v5_1_7.a upgrade.
MERGING

**Pull request merged**
