### PR TITLE
InnerException improvements

### PR DESCRIPTION
**Pull request by kellyroach**
Ported recent Xamarin InnerException improvement into crittercism-unity-ios .
Tested OK.  Viewed HE and crash report inner exceptions stack traces on platform.

Planning on doing similarly for crittercism-unity-android in different P.R.

### CODE REVIEW

**Comment by dshirley** [comment]
Other than whitespace issues.  LGTM.

Merge when you're ready

**Comment by kellyroach** [comment]
In my experience, it is best to disable all tabs in all code editors, because they're not
uniform in agreement what the tab means.  I expect to replace all the tabs by spaces
in future if I have my way.  I imagine our customers can survive and work around the
whitespace issues until then.

**Comment by dshirley** [comment]
That's fine.  Please feel free to replace all hard tabs with spaces.

**Comment by pgorrow** [comment]
As a consumer of the library, I'd prefer the use of tabs configured as standard out of the box for Unity/Mono.

**Comment by dshirley** [comment]
@pgorrow What is the out of the box configuration?

**Pull request merged**
